// Test generated by RoostGPT for test test2 using AI Type Open AI and AI Model gpt-4

package com.company.internationalizationtaticfilesandresources.handler;

import com.company.internationalizationtaticfilesandresources.dto.ResponseMessage;
import com.company.internationalizationtaticfilesandresources.exception.UploadFailedException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class GlobalExceptionHandler_handle_a6daf70424_Test {

    private GlobalExceptionHandler globalExceptionHandler;

    @BeforeEach
    public void setup() {
        globalExceptionHandler = new GlobalExceptionHandler();
    }

    @Test
    public void testHandle() {
        ResponseEntity<ResponseMessage> response = globalExceptionHandler.handle();
        assertEquals(HttpStatus.INTERNAL_SERVER_ERROR, response.getStatusCode());
        assertEquals("File size to large!", response.getBody().getMessage().toString());
    }

    @Test
    public void testHandleWithException() {
        try {
            throw new UploadFailedException("File size to large!");
        } catch (UploadFailedException e) {
            ResponseEntity<ResponseMessage> response = globalExceptionHandler.handle();
            assertEquals(HttpStatus.INTERNAL_SERVER_ERROR, response.getStatusCode());
            assertEquals("File size to large!", response.getBody().getMessage().toString());
        }
    }
}
