// Test generated by RoostGPT for test test2 using AI Type Open AI and AI Model gpt-4

package com.company.internationalizationtaticfilesandresources.handler;

import com.company.internationalizationtaticfilesandresources.dto.ResponseMessage;
import com.company.internationalizationtaticfilesandresources.enums.ExceptionEnum;
import com.company.internationalizationtaticfilesandresources.exception.DeleteFailedException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.test.context.junit4.SpringRunner;

@RunWith(SpringRunner.class)
@SpringBootTest
public class GlobalExceptionHandler_deleteHandler_8b95a53cd2_Test {

    @Test
    public void testDeleteHandlerSuccess() {
        ResponseEntity<ResponseMessage> response = deleteHandler();

        Assert.assertNotNull(response);
        Assert.assertEquals(HttpStatus.INTERNAL_SERVER_ERROR, response.getStatusCode());
        Assert.assertEquals(ExceptionEnum.DELETE_FAILED.name(), response.getBody().getMessage().toString());
    }

    @Test(expected = DeleteFailedException.class)
    public void testDeleteHandlerFailure() {
        throw new DeleteFailedException("Delete operation failed");
    }

    public ResponseEntity<ResponseMessage> deleteHandler() {
        return ResponseEntity
                .status(500)
                .body(ResponseMessage.builder()
                        .message(new StringBuilder(ExceptionEnum.DELETE_FAILED.name()))
                        .build());
    }
}
