// Test generated by RoostGPT for test test2 using AI Type Open AI and AI Model gpt-4

package com.company.internationalizationtaticfilesandresources.handler;

import com.company.internationalizationtaticfilesandresources.dto.ResponseMessage;
import com.company.internationalizationtaticfilesandresources.enums.ExceptionEnum;
import com.company.internationalizationtaticfilesandresources.exception.NotFoundException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class GlobalExceptionHandler_NotFoundHandler_0b0b033538_Test {

    private GlobalExceptionHandler globalExceptionHandler;

    @BeforeEach
    void setUp() {
        globalExceptionHandler = new GlobalExceptionHandler();
    }

    @Test
    void testNotFoundHandler() {
        ResponseEntity<ResponseMessage> responseEntity = globalExceptionHandler.NotFoundHandler();
        assertEquals(HttpStatus.NOT_FOUND, responseEntity.getStatusCode());
        assertEquals(ExceptionEnum.NOT_FOUND_FILE.name(), responseEntity.getBody().getMessage().toString());
    }

    @Test
    void testNotFoundHandlerWithDifferentStatus() {
        ResponseEntity<ResponseMessage> responseEntity = globalExceptionHandler.NotFoundHandler();
        assertNotEquals(HttpStatus.OK, responseEntity.getStatusCode());
    }
}
