// Test generated by RoostGPT for test test2 using AI Type Open AI and AI Model gpt-4

package com.company.internationalizationtaticfilesandresources.handler;

import com.company.internationalizationtaticfilesandresources.dto.ResponseMessage;
import com.company.internationalizationtaticfilesandresources.enums.ExceptionEnum;
import com.company.internationalizationtaticfilesandresources.exception.UploadFailedException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class GlobalExceptionHandler_uploadHandler_bf5af06614_Test {

    private GlobalExceptionHandler globalExceptionHandler;

    @BeforeEach
    public void setup() {
        globalExceptionHandler = new GlobalExceptionHandler();
    }

    @Test
    public void testUploadHandler() {
        ResponseEntity<ResponseMessage> response = globalExceptionHandler.uploadHandler();
        assertEquals(HttpStatus.NOT_FOUND, response.getStatusCode());
        assertEquals(ExceptionEnum.UPLOAD_FAILED.name(), response.getBody().getMessage().toString());
    }

    @Test
    public void testUploadHandlerException() {
        try {
            ResponseEntity<ResponseMessage> response = globalExceptionHandler.uploadHandler();
            throw new UploadFailedException("Upload Failed");
        } catch (UploadFailedException e) {
            assertEquals("Upload Failed", e.getMessage());
        }
    }
}
