// Test generated by RoostGPT for test test2 using AI Type Open AI and AI Model gpt-4

package com.company.internationalizationtaticfilesandresources.exception;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class DownloadFailedException_DownloadFailedException_cef8ed63d8_Test {

    private DownloadFailedException downloadFailedException;

    @BeforeEach
    public void setUp() {
        downloadFailedException = new DownloadFailedException();
    }

    @Test
    public void testDownloadFailedException() {
        // Assert that the exception message matches the expected value
        assertEquals(ExceptionEnum.DOWNLOAD_FAILED.name(), downloadFailedException.getMessage());
    }

    @Test
    public void testExceptionEnum() {
        // Assert that the exception enum matches the expected value
        assertEquals(ExceptionEnum.DOWNLOAD_FAILED, ExceptionEnum.valueOf(downloadFailedException.getMessage()));
    }
}
