// Test generated by RoostGPT for test test2 using AI Type Open AI and AI Model gpt-4

package com.company.internationalizationtaticfilesandresources.exception;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

@ExtendWith(MockitoExtension.class)
public class DownloadFailedException_DownloadFailedException_cef8ed63d8_Test {

    private DownloadFailedException downloadFailedException;

    @BeforeEach
    public void setUp() {
        downloadFailedException = new DownloadFailedException();
    }

    @Test
    public void testDownloadFailedExceptionMessage() {
        // Assuming that the DownloadFailedException's message is a constant string "DOWNLOAD_FAILED"
        assertEquals("DOWNLOAD_FAILED", downloadFailedException.getMessage());
    }

    @Test
    public void testDownloadFailedExceptionNotNull() {
        assertNotNull(downloadFailedException.getMessage());
    }
}
