// Test generated by RoostGPT for test test2 using AI Type Open AI and AI Model gpt-4

package com.company.internationalizationtaticfilesandresources.exception;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import com.company.internationalizationtaticfilesandresources.enums.ExceptionEnum;

public class DownloadFailedException_DownloadFailedException_cef8ed63d8_Test {

    private DownloadFailedException downloadFailedException;

    @BeforeEach
    public void setup() {
        downloadFailedException = new DownloadFailedException();
    }

    @Test
    public void testDownloadFailedException() {
        // Test that the correct message is set in the exception
        assertEquals(ExceptionEnum.DOWNLOAD_FAILED.name(), downloadFailedException.getMessage());
    }

    @Test
    public void testDownloadFailedException_notEqual() {
        // Test that the message is not set to a different value
        assertNotEquals(ExceptionEnum.OTHER_ERROR.name(), downloadFailedException.getMessage());
    }
}
