// Test generated by RoostGPT for test test2 using AI Type Open AI and AI Model gpt-4

package com.company.internationalizationtaticfilesandresources.exception;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import com.company.internationalizationtaticfilesandresources.enums.ExceptionEnum;

public class UploadFailedException_UploadFailedException_78b326900b_Test {

    private UploadFailedException uploadFailedException;

    @BeforeEach
    public void setUp() {
        uploadFailedException = new UploadFailedException();
    }

    @Test
    public void testUploadFailedException() {
        String expectedMessage = ExceptionEnum.UPLOAD_FAILED.name();
        String actualMessage = uploadFailedException.getMessage();
        assertEquals(expectedMessage, actualMessage, "Expected and actual messages should be same");
    }

    @Test
    public void testUploadFailedExceptionWithDifferentEnum() {
        String expectedMessage = ExceptionEnum.UPLOAD_FAILED.name();
        String actualMessage = new UploadFailedException(ExceptionEnum.DATABASE_ERROR.name()).getMessage();
        assertNotEquals(expectedMessage, actualMessage, "Expected and actual messages should not be same");
    }
}
