// Test generated by RoostGPT for test test2 using AI Type Open AI and AI Model gpt-4

package com.company.internationalizationtaticfilesandresources.exception;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class UploadFailedException_UploadFailedException_78b326900b_Test {

    private UploadFailedException uploadFailedException;

    @BeforeEach
    public void setUp() {
        uploadFailedException = new UploadFailedException();
    }

    @Test
    public void testUploadFailedException() {
        assertEquals(ExceptionEnum.UPLOAD_FAILED.name(), uploadFailedException.getMessage());
    }

    @Test
    public void testUploadFailedExceptionWithDifferentException() {
        // TODO: Change the exception enum to a different one for this test
        ExceptionEnum differentException = ExceptionEnum.DIFFERENT_EXCEPTION;
        uploadFailedException = new UploadFailedException(differentException);
        assertEquals(differentException.name(), uploadFailedException.getMessage());
    }
}
