// Test generated by RoostGPT for test test2 using AI Type Open AI and AI Model gpt-4

package com.company.internationalizationtaticfilesandresources.service.impl;

import com.company.internationalizationtaticfilesandresources.dto.ResponseMessage;
import com.company.internationalizationtaticfilesandresources.exception.DeleteFailedException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
public class IFileStorageService_delete_582328788e_Test {

    @Mock
    private Path ROOT;

    @InjectMocks
    private FileStorageService fileStorageService;

    @BeforeEach
    public void setUp() {
        ROOT = Paths.get("root");
    }

    @Test
    public void testDelete_Success() throws Exception {
        String fileName = "testFile.txt";
        when(Files.deleteIfExists(ROOT.resolve(fileName))).thenReturn(true);

        ResponseMessage responseMessage = fileStorageService.delete(fileName);

        assertEquals("DELETE_SUCCESSFULLY", responseMessage.getMessage());
    }

    @Test
    public void testDelete_FileNotExists() throws Exception {
        String fileName = "testFile.txt";
        when(Files.deleteIfExists(ROOT.resolve(fileName))).thenReturn(false);

        assertThrows(DeleteFailedException.class, () -> {
            fileStorageService.delete(fileName);
        });
    }

    @Test
    public void testDelete_IOException() throws Exception {
        String fileName = "testFile.txt";
        when(Files.deleteIfExists(ROOT.resolve(fileName))).thenThrow(new IOException());

        assertThrows(DeleteFailedException.class, () -> {
            fileStorageService.delete(fileName);
        });
    }
}
