// Test generated by RoostGPT for test test2 using AI Type Open AI and AI Model gpt-4

package com.company.internationalizationtaticfilesandresources.service.impl;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.boot.test.context.SpringBootTest;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.*;

@SpringBootTest
public class IFileStorageService_init_0ef02243a9_Test {

    @InjectMocks
    private FileStorageService fileStorageService;

    @Mock
    private Path ROOT;

    private AutoCloseable closeable;

    @BeforeEach
    public void setup() {
        closeable = MockitoAnnotations.openMocks(this);
    }

    @AfterEach
    public void closeService() throws Exception {
        closeable.close();
    }

    @Test
    public void testInit_success() {
        doReturn(Paths.get("/test")).when(ROOT).getRoot();

        fileStorageService.init();

        verify(ROOT, times(1)).getRoot();
    }

    @Test
    public void testInit_failure() throws IOException {
        doThrow(IOException.class).when(ROOT).getRoot();

        assertThrows(RuntimeException.class, () -> fileStorageService.init());

        verify(ROOT, times(1)).getRoot();
    }
}
