// Test generated by RoostGPT for test test2 using AI Type Open AI and AI Model gpt-4

package com.company.internationalizationtaticfilesandresources.controller;

import com.company.internationalizationtaticfilesandresources.dto.ResponseMessage;
import com.company.internationalizationtaticfilesandresources.service.FileStorageService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class FileController_deleteFile_08dfb3ef1b_Test {

    @Mock
    private FileStorageService fileStorageService;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testDeleteFile_Success() {
        String fileName = "testFile.txt";
        ResponseMessage responseMessage = new ResponseMessage("File deleted successfully");
        when(fileStorageService.delete(fileName)).thenReturn(responseMessage);

        ResponseEntity<ResponseMessage> expectedResponse = ResponseEntity.status(HttpStatus.OK).body(responseMessage);
        ResponseEntity<ResponseMessage> actualResponse = deleteFile(fileName);

        assertEquals(expectedResponse, actualResponse);
    }

    @Test
    public void testDeleteFile_Failure() {
        String fileName = "nonExistentFile.txt";
        ResponseMessage responseMessage = new ResponseMessage("File not found");
        when(fileStorageService.delete(fileName)).thenReturn(responseMessage);

        ResponseEntity<ResponseMessage> expectedResponse = ResponseEntity.status(HttpStatus.OK).body(responseMessage);
        ResponseEntity<ResponseMessage> actualResponse = deleteFile(fileName);

        assertEquals(expectedResponse, actualResponse);
    }

    public ResponseEntity<ResponseMessage> deleteFile(String fileName) {
        return ResponseEntity.status(HttpStatus.OK)
                .body(fileStorageService.delete(fileName));
    }
}
