// Test generated by RoostGPT for test uploadmultipartfile using AI Type Open AI and AI Model gpt-4

package com.company.internationalizationtaticfilesandresources.controller;

import com.company.internationalizationtaticfilesandresources.dto.ResponseMessage;
import com.company.internationalizationtaticfilesandresources.service.FileStorageService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

public class FileController_deleteFile_25c016815d_Test {

    @InjectMocks
    private FileController fileController;

    @Mock
    private FileStorageService fileStorageService;

    @BeforeEach
    void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testDeleteFile_Success() {
        String fileName = "test.txt";
        ResponseMessage responseMessage = new ResponseMessage("File deleted successfully");
        
        when(fileStorageService.delete(fileName)).thenReturn(responseMessage);

        ResponseEntity<ResponseMessage> result = fileController.deleteFile(fileName);

        verify(fileStorageService, times(1)).delete(fileName);
        assertEquals(HttpStatus.OK, result.getStatusCode());
        assertEquals(responseMessage, result.getBody());
    }

    @Test
    public void testDeleteFile_Failure() {
        String fileName = "nonexistent.txt";
        ResponseMessage responseMessage = new ResponseMessage("File not found");

        when(fileStorageService.delete(fileName)).thenReturn(responseMessage);

        ResponseEntity<ResponseMessage> result = fileController.deleteFile(fileName);

        verify(fileStorageService, times(1)).delete(fileName);
        assertEquals(HttpStatus.OK, result.getStatusCode());
        assertEquals(responseMessage, result.getBody());
    }
}
