// Test generated by RoostGPT for test test2 using AI Type Open AI and AI Model gpt-4

package com.company.internationalizationtaticfilesandresources.controller;

import com.company.internationalizationtaticfilesandresources.service.FileStorageService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.http.ResponseEntity;
import java.nio.file.Path;
import java.util.stream.Stream;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class FileController_getFile_7a9b8d2dbd_Test {

    @Mock
    private FileStorageService fileStorageService;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testGetFile_Success() {
        Stream<Path> expectedStream = Stream.of(Path.of("/file1.txt"), Path.of("/file2.txt"));
        when(fileStorageService.getFilesStream()).thenReturn(expectedStream);

        ResponseEntity<Stream<Path>> result = getFile();

        assertEquals(ResponseEntity.ok(expectedStream), result);
    }

    @Test
    public void testGetFile_EmptyStream() {
        Stream<Path> expectedStream = Stream.empty();
        when(fileStorageService.getFilesStream()).thenReturn(expectedStream);

        ResponseEntity<Stream<Path>> result = getFile();

        assertEquals(ResponseEntity.ok(expectedStream), result);
    }

    public ResponseEntity<Stream<Path>> getFile() {
        return ResponseEntity.ok(fileStorageService.getFilesStream());
    }
}
