// Test generated by RoostGPT for test test2 using AI Type Open AI and AI Model gpt-4

package com.company.internationalizationtaticfilesandresources.controller;

import com.company.internationalizationtaticfilesandresources.dto.ResponseMessage;
import com.company.internationalizationtaticfilesandresources.service.FileStorageService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.when;

public class FileController_deleteFile_08dfb3ef1b_Test {

    @InjectMocks
    FileController fileController;

    @Mock
    FileStorageService fileStorageService;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testDeleteFile_Success() {
        ResponseMessage responseMessage = new ResponseMessage("File deleted successfully");
        when(fileStorageService.delete(anyString())).thenReturn(responseMessage);

        ResponseEntity<ResponseMessage> response = fileController.deleteFile("test.txt");

        assertEquals(HttpStatus.OK, response.getStatusCode());
        assertEquals("File deleted successfully", response.getBody().getMessage());
    }

    @Test
    public void testDeleteFile_Failure() {
        ResponseMessage responseMessage = new ResponseMessage("File not found");
        when(fileStorageService.delete(anyString())).thenReturn(responseMessage);

        ResponseEntity<ResponseMessage> response = fileController.deleteFile("nonexistent.txt");

        assertEquals(HttpStatus.OK, response.getStatusCode());
        assertEquals("File not found", response.getBody().getMessage());
    }
}
